const prisma = require('../../config/db');

const getAll = async (user) => {
  const where = user.role === 'CUSTOMER' ? { customerId: user.customer.id } : {};
  return await prisma.estimate.findMany({
    where,
    include: { customer: true, items: true },
    orderBy: { createdAt: 'desc' }
  });
};

const create = async (estimateData) => {
  const { items, projectTitle, notes, customerId, total, status } = estimateData;
  
  const mappedItems = items ? items.map(item => ({
    description: item.desc || 'No description',
    quantity: parseInt(item.qty) || 1,
    unitPrice: parseFloat(item.price) || 0,
    total: parseFloat(item.qty * item.price) || 0
  })) : [];

  return await prisma.estimate.create({
    data: {
      customerId: parseInt(customerId),
      projectTitle,
      notes,
      status: status || 'PENDING',
      totalAmount: total || 0,
      items: {
        create: mappedItems
      }
    },
    include: { items: true, customer: true }
  });
};

const update = async (id, estimateData) => {
  const { items, projectTitle, notes, total, status } = estimateData;
  const estimateId = parseInt(id);

  // 1. Delete existing items
  await prisma.estimateItem.deleteMany({ where: { estimateId } });

  // 2. Map new items
  const mappedItems = items ? items.map(item => ({
    description: item.desc || 'No description',
    quantity: parseInt(item.qty) || 1,
    unitPrice: parseFloat(item.price) || 0,
    total: parseFloat(item.qty * item.price) || 0
  })) : [];

  // 3. Update estimate and create new items
  return await prisma.estimate.update({
    where: { id: estimateId },
    data: {
      projectTitle,
      notes,
      status: status === 'Draft' ? 'PENDING' : 'REVISED', // Business rule: edits move it to REVISED unless drafting
      totalAmount: total || 0,
      items: {
        create: mappedItems
      }
    },
    include: { items: true, customer: true }
  });
};

const approve = async (id) => {
  const estimate = await prisma.estimate.update({
    where: { id: parseInt(id) },
    data: { status: 'APPROVED' },
    include: { customer: true, items: true }
  });

  // Automatically create a job if it doesn't exist
  const existingJob = await prisma.job.findUnique({ where: { estimateId: estimate.id } });
  if (!existingJob) {
    await prisma.job.create({
      data: {
        title: estimate.projectTitle || `${estimate.customer.name}'s Service Job`,
        description: estimate.notes || 'Autogenerated from approved estimate',
        customerId: estimate.customerId,
        estimateId: estimate.id,
        status: 'SCHEDULED'
      }
    });
  }

  return estimate;
};

module.exports = { getAll, create, update, approve };
